added dropdown headers and fixed window.location.replace
sakshiarora04/just-movie pull request #7
Opened 2023-07-04 11:37 UTC by Andysu7117

Also changed  the location paths for images

2023-07-04 11:51 UTC, shimna-puthanayil commented on display-search.html
> +                  <li><a href="#">Popular</a></li>
Change the popular to top rated

2023-07-04 11:55 UTC, shimna-puthanayil requested changes
Make changes on all lines i have commented

2023-07-05 04:41 UTC, Andysu7117 commented on display-search.html
> +                  <li><a href="#">Popular</a></li>
Changed to Top Rated

2023-07-06 08:13 UTC, shimna-puthanayil approved these changes
Approved

2023-07-06 08:36 UTC, merged